"use client";
import { useMemo, useState, useTransition } from "react";
import { GripVertical, Pencil, Plus, Search, Trash2, X } from "lucide-react";
import { useRouter } from "next/navigation";
import ImageUploadField from "./ImageUploadField";
import { deleteCareerPath, deleteCatalogCourse, deleteJourney, reorderCareerPaths, reorderCourses, reorderJourneys, saveCareerPath, saveCourse, saveJourney } from "@/lib/actions/admin/catalog";

type Kind="paths"|"courses"|"journeys";
type Row=Record<string, any>;
const empty={paths:{title:"",slug:"",short_title:"",description:"",image_url:"",image_path:"",is_active:true,display_order:1},courses:{station_id:"",title:"",slug:"",description:"",image_url:"",image_path:"",icon_url:"",icon_path:"",price:0,currency:"SAR",duration_hours:0,projects_count:0,level:"مبتدئ",journey_type:"career_path",status:"draft",is_active:true,is_featured:false,display_order:1},journeys:{course_id:"",title:"",slug:"",journey_type:"fundamental",description:"",duration_hours:0,price:0,currency:"SAR",registration_required:true,status:"available",start_date:"",end_date:"",is_active:true,display_order:1}};

export default function CatalogManager({kind,initialRows,stations=[],courses=[]}:{kind:Kind;initialRows:Row[];stations?:Row[];courses?:Row[]}){
 const router=useRouter(); const [rows,setRows]=useState(initialRows); const [query,setQuery]=useState(""); const [editing,setEditing]=useState<Row|null>(null); const [dragged,setDragged]=useState<string|null>(null); const [pending,startTransition]=useTransition();
 const labels={paths:{title:"المسارات المهنية",single:"مسار",add:"إضافة مسار"},courses:{title:"الكورسات",single:"كورس",add:"إضافة كورس"},journeys:{title:"الرحلات",single:"رحلة",add:"إضافة رحلة"}}[kind];
 const filtered=useMemo(()=>rows.filter(r=>(`${r.title||""} ${r.slug||""}`).toLowerCase().includes(query.toLowerCase())),[rows,query]);
 function open(row?:Row){setEditing(row?{...row}:{...empty[kind],display_order:rows.length+1});}
 function submit(){if(!editing)return;startTransition(async()=>{const fn=kind==="paths"?saveCareerPath:kind==="courses"?saveCourse:saveJourney;const result=await fn(editing);if(!result.success)return alert(result.message);setEditing(null);router.refresh();window.location.reload();});}
 function remove(row:Row){if(!confirm(`هل تريدين حذف ${labels.single} «${row.title}»؟`))return;startTransition(async()=>{const fn=kind==="paths"?deleteCareerPath:kind==="courses"?deleteCatalogCourse:deleteJourney;const result=await fn(row.id);if(!result.success)return alert(result.message);setRows(v=>v.filter(x=>x.id!==row.id));router.refresh();});}
 function drop(target:string){if(!dragged||dragged===target)return;const next=[...rows];const a=next.findIndex(x=>x.id===dragged),b=next.findIndex(x=>x.id===target);const [item]=next.splice(a,1);next.splice(b,0,item);setRows(next);setDragged(null);startTransition(async()=>{const fn=kind==="paths"?reorderCareerPaths:kind==="courses"?reorderCourses:reorderJourneys;const result=await fn(next.map(x=>x.id));if(!result.success)alert(result.message);router.refresh();});}
 return <div className="space-y-5"><div className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div className="relative max-w-md flex-1"><Search className="absolute right-3 top-3 h-5 w-5 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`البحث في ${labels.title}`} className="h-11 w-full rounded-xl border border-slate-200 pr-10 pl-3 outline-none focus:border-[#F7B548]"/></div><button onClick={()=>open()} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-[#F7B548] px-5 font-black text-[#07152E]"><Plus className="h-5 w-5"/>{labels.add}</button></div>
 <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[780px] text-right"><thead className="bg-slate-50 text-sm text-slate-500"><tr><th className="w-12 p-4"></th><th className="p-4">الاسم</th><th className="p-4">الرابط المختصر</th><th className="p-4">التصنيف</th><th className="p-4">الحالة</th><th className="p-4">الترتيب</th><th className="p-4">الإجراءات</th></tr></thead><tbody>{filtered.map(row=><tr key={row.id} draggable onDragStart={()=>setDragged(row.id)} onDragOver={e=>e.preventDefault()} onDrop={()=>drop(row.id)} className="border-t border-slate-100 hover:bg-slate-50/70"><td className="p-4 text-slate-400"><GripVertical className="h-5 w-5 cursor-grab"/></td><td className="p-4"><div className="font-black text-[#07152E]">{row.title}</div><div className="max-w-sm truncate text-xs text-slate-500">{row.description||"بدون وصف"}</div></td><td className="p-4 font-mono text-xs text-slate-500">{row.slug}</td><td className="p-4 text-sm text-slate-600">{kind==="courses"?(stations.find(s=>s.id===row.station_id)?.title||row.journey_type):kind==="journeys"?(courses.find(c=>c.id===row.course_id)?.title||row.journey_type):"مسار مهني"}</td><td className="p-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${(row.is_active!==false&&row.status!=="archived")?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500"}`}>{row.status||((row.is_active!==false)?"نشط":"غير نشط")}</span></td><td className="p-4">{row.display_order}</td><td className="p-4"><div className="flex gap-2"><button onClick={()=>open(row)} className="rounded-lg border border-slate-200 p-2 text-blue-600 hover:bg-blue-50"><Pencil className="h-4 w-4"/></button><button onClick={()=>remove(row)} className="rounded-lg border border-slate-200 p-2 text-red-600 hover:bg-red-50"><Trash2 className="h-4 w-4"/></button></div></td></tr>)}</tbody></table></div>{filtered.length===0&&<div className="p-16 text-center text-slate-500">لا توجد بيانات مطابقة.</div>}</div>
 {editing&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/50 p-4"><div className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-3xl bg-white shadow-2xl"><div className="sticky top-0 z-10 flex items-center justify-between border-b bg-white px-6 py-5"><h2 className="text-xl font-black text-[#07152E]">{editing.id?`تعديل ${labels.single}`:labels.add}</h2><button onClick={()=>setEditing(null)} className="rounded-lg p-2 hover:bg-slate-100"><X/></button></div><div className="grid gap-5 p-6 md:grid-cols-2">
 <Field label="الاسم" value={editing.title} set={v=>setEditing({...editing,title:v})}/><Field label="Slug" value={editing.slug} set={v=>setEditing({...editing,slug:v})}/>
 {kind==="paths"&&<><Field label="الاسم المختصر" value={editing.short_title||""} set={v=>setEditing({...editing,short_title:v})}/><ImageUploadField label="صورة المسار" value={editing.image_url||""} folder="career-paths" onChange={(url,path)=>setEditing({...editing,image_url:url,image_path:path||editing.image_path})}/></>}
 {kind==="courses"&&<><Select label="المحطة التابعة للمسار" value={editing.station_id||""} set={v=>setEditing({...editing,station_id:v})} options={[{value:"",label:"بدون محطة"},...stations.map(s=>({value:s.id,label:s.title}))]}/><Select label="نوع الكورس" value={editing.journey_type} set={v=>setEditing({...editing,journey_type:v})} options={[{value:"career_path",label:"رحلة احتراف"},{value:"workshop",label:"ورشة يوم واحد"},{value:"free",label:"مجاني"}]}/><Field label="المدة بالساعات" type="number" value={editing.duration_hours} set={v=>setEditing({...editing,duration_hours:Number(v)})}/><Field label="السعر" type="number" value={editing.price} set={v=>setEditing({...editing,price:Number(v)})}/><Field label="عدد المشاريع" type="number" value={editing.projects_count} set={v=>setEditing({...editing,projects_count:Number(v)})}/><Select label="الحالة" value={editing.status} set={v=>setEditing({...editing,status:v})} options={[{value:"draft",label:"مسودة"},{value:"published",label:"منشور"},{value:"archived",label:"مؤرشف"}]}/><ImageUploadField label="صورة الكورس" value={editing.image_url||""} folder="courses" onChange={(url,path)=>setEditing({...editing,image_url:url,image_path:path||editing.image_path})}/><ImageUploadField label="أيقونة الكورس" value={editing.icon_url||""} folder="course-icons" onChange={(url,path)=>setEditing({...editing,icon_url:url,icon_path:path||editing.icon_path})}/></>}
 {kind==="journeys"&&<><Select label="الكورس" value={editing.course_id||""} set={v=>setEditing({...editing,course_id:v})} options={[{value:"",label:"اختاري الكورس"},...courses.map(c=>({value:c.id,label:c.title}))]}/><Select label="نوع الرحلة" value={editing.journey_type} set={v=>setEditing({...editing,journey_type:v})} options={[{value:"fundamental",label:"تأسيسية"},{value:"advanced",label:"متقدمة"},{value:"integrated",label:"متكاملة"}]}/><Field label="المدة بالساعات" type="number" value={editing.duration_hours} set={v=>setEditing({...editing,duration_hours:Number(v)})}/><Field label="السعر" type="number" value={editing.price} set={v=>setEditing({...editing,price:Number(v)})}/><Select label="الحالة" value={editing.status} set={v=>setEditing({...editing,status:v})} options={[{value:"draft",label:"مسودة"},{value:"coming_soon",label:"قريباً"},{value:"available",label:"متاحة"},{value:"closed",label:"مغلقة"},{value:"archived",label:"مؤرشفة"}]}/><Field label="تاريخ البداية" type="datetime-local" value={editing.start_date?String(editing.start_date).slice(0,16):""} set={v=>setEditing({...editing,start_date:v?new Date(v).toISOString():""})}/></>}
 <div className="md:col-span-2"><label className="mb-2 block text-sm font-bold text-[#07152E]">الوصف</label><textarea rows={4} value={editing.description||""} onChange={e=>setEditing({...editing,description:e.target.value})} className="w-full rounded-xl border border-slate-200 p-3 outline-none focus:border-[#F7B548]"/></div><Field label="الترتيب" type="number" value={editing.display_order} set={v=>setEditing({...editing,display_order:Number(v)})}/><Toggle label="نشط" checked={editing.is_active!==false} set={v=>setEditing({...editing,is_active:v})}/></div><div className="sticky bottom-0 flex justify-end gap-3 border-t bg-white px-6 py-4"><button onClick={()=>setEditing(null)} className="rounded-xl border px-6 py-3 font-bold">إلغاء</button><button disabled={pending} onClick={submit} className="rounded-xl bg-[#F7B548] px-8 py-3 font-black text-[#07152E] disabled:opacity-50">{pending?"جاري الحفظ...":"حفظ"}</button></div></div></div>}</div>;
}
function Field({label,value,set,type="text"}:{label:string;value:any;set:(v:string)=>void;type?:string}){return <div><label className="mb-2 block text-sm font-bold text-[#07152E]">{label}</label><input type={type} value={value??""} onChange={e=>set(e.target.value)} className="h-11 w-full rounded-xl border border-slate-200 px-3 outline-none focus:border-[#F7B548]"/></div>}
function Select({label,value,set,options}:{label:string;value:string;set:(v:string)=>void;options:{value:string;label:string}[]}){return <div><label className="mb-2 block text-sm font-bold text-[#07152E]">{label}</label><select value={value||""} onChange={e=>set(e.target.value)} className="h-11 w-full rounded-xl border border-slate-200 bg-white px-3 outline-none focus:border-[#F7B548]">{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></div>}
function Toggle({label,checked,set}:{label:string;checked:boolean;set:(v:boolean)=>void}){return <label className="flex h-11 items-center gap-3 self-end rounded-xl border border-slate-200 px-4"><input type="checkbox" checked={checked} onChange={e=>set(e.target.checked)} className="h-4 w-4"/><span className="font-bold text-[#07152E]">{label}</span></label>}
