"use client";
import { Download,ExternalLink,Search,Star } from "lucide-react";
import { useMemo,useState,type ReactNode } from "react";
import SurveyVisibilityToggle from "@/components/admin/courses/SurveyVisibilityToggle";
import type { SurveysDashboardData } from "@/lib/actions/admin/surveys-dashboard";

export default function SurveysDashboard({initialData}:{initialData:SurveysDashboardData}){
 const[pathFilter,setPathFilter]=useState("all");const[search,setSearch]=useState("");
 const rows=useMemo(()=>{const q=search.trim().toLowerCase();return initialData.rows.filter(r=>(pathFilter==="all"||(r.pathId??"unassigned")===pathFilter)&&(!q||[r.studentName,r.studentEmail,r.courseTitle,r.courseCode,r.comment].filter(Boolean).join(" ").toLowerCase().includes(q)))},[initialData.rows,pathFilter,search]);
 function exportCsv(){const h=["الطالب","البريد الإلكتروني","المسار","الكورس","كود الكورس","التقييم","التعليق","التاريخ","Google Form","الرئيسية","صفحة الكورس"];const d=rows.map(r=>[r.studentName,r.studentEmail,r.pathTitle,r.courseTitle,r.courseCode??"",String(r.rating),r.comment??"",date(r.submittedAt),r.detailedSurveyCompleted?"مكتمل":"لم يكتمل",r.showOnHome?"نعم":"لا",r.showOnCourse?"نعم":"لا"]);const csv=[h,...d].map(x=>x.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(",")).join("\n");const b=new Blob([`\uFEFF${csv}`],{type:"text/csv;charset=utf-8"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="masar-surveys.csv";a.click();URL.revokeObjectURL(u)}
 return <section dir="rtl" className="space-y-6">
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card l="إجمالي التقييمات" v={initialData.statistics.total}/><Card l="متوسط التقييم" v={`${initialData.statistics.average}/5`}/><Card l="Google Form مكتمل" v={initialData.statistics.detailedCompleted}/><Card l="معروضة في الرئيسية" v={initialData.statistics.showOnHome}/></div>
  <div className="rounded-2xl border bg-white p-4 shadow-sm">
   <div className="flex flex-wrap gap-2"><Filter a={pathFilter==="all"} f={()=>setPathFilter("all")}>الكل ({initialData.rows.length})</Filter>{initialData.paths.map(p=><Filter key={p.id} a={pathFilter===p.id} f={()=>setPathFilter(p.id)}>{p.title} ({p.count})</Filter>)}</div>
   <div className="mt-4 flex flex-wrap gap-3"><label className="flex min-w-[280px] flex-1 items-center rounded-xl border bg-slate-50 px-4"><Search className="h-4 w-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث باسم الطالب أو الكورس أو كود الكورس..." className="h-11 w-full bg-transparent px-3 text-sm font-bold outline-none"/></label><button onClick={exportCsv} className="inline-flex h-11 items-center gap-2 rounded-xl bg-[#07152E] px-5 text-sm font-black text-white"><Download className="h-4 w-4"/>تصدير CSV</button></div>
  </div>
  <div className="overflow-x-auto rounded-2xl border bg-white shadow-sm"><table className="w-full min-w-[1450px] text-center"><thead className="bg-slate-50"><tr>{["الطالب","المسار","الكورس","كود الكورس","التقييم","التعليق","التاريخ","Google Form","الرئيسية","صفحة الكورس","الإجراءات"].map(h=><th key={h} className="px-4 py-4 text-xs font-black text-slate-500">{h}</th>)}</tr></thead><tbody>
   {rows.map(r=><tr key={r.id} className="border-t"><td className="px-4 py-4 text-right"><b>{r.studentName}</b><div className="text-[10px] text-slate-400">{r.studentEmail}</div></td><Cell>{r.pathTitle}</Cell><Cell>{r.courseTitle}</Cell><Cell><span className="rounded-lg bg-[#FFF5DD] px-3 py-1 text-xs font-black text-[#C88712]">{r.courseCode||"—"}</span></Cell><Cell><span className="inline-flex items-center gap-1 font-black text-[#C88712]"><Star className="h-4 w-4"/>{r.rating}/5</span></Cell><td className="max-w-[300px] px-4 py-4 text-right text-sm text-slate-600">{r.comment||"—"}</td><Cell>{date(r.submittedAt)}</Cell><Cell>{r.detailedSurveyCompleted?"مكتمل":"لم يكتمل"}</Cell><Cell><SurveyVisibilityToggle surveyId={r.id} initialShowOnHome={r.showOnHome} initialShowOnCourse={r.showOnCourse} type="home"/></Cell><Cell><SurveyVisibilityToggle surveyId={r.id} initialShowOnHome={r.showOnHome} initialShowOnCourse={r.showOnCourse} type="course"/></Cell><Cell>{r.surveyUrl?<a href={r.surveyUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg bg-[#F7B548] px-3 py-2 text-xs font-black text-[#07152E]"><ExternalLink className="h-4 w-4"/>فتح الاستبيان</a>:<span className="text-xs text-slate-400">غير مفعّل</span>}</Cell></tr>)}
   {!rows.length&&<tr><td colSpan={11} className="p-12 font-bold text-slate-500">لا توجد نتائج مطابقة.</td></tr>}
  </tbody></table></div>
 </section>
}
function date(v:string|null){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("ar-EG",{day:"numeric",month:"short",year:"numeric"}).format(d)}
function Cell({children}:{children:ReactNode}){return <td className="whitespace-nowrap px-4 py-4 text-sm font-bold text-slate-600">{children}</td>}
function Card({l,v}:{l:string;v:ReactNode}){return <div className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-xs font-bold text-slate-500">{l}</p><p className="mt-2 text-3xl font-black text-[#07152E]">{v}</p></div>}
function Filter({a,f,children}:{a:boolean;f:()=>void;children:ReactNode}){return <button onClick={f} className={`rounded-full px-4 py-2 text-xs font-black ${a?"bg-[#07152E] text-white":"bg-slate-100 text-slate-600"}`}>{children}</button>}